config/routes.rb
Whenbus::Application.routes.draw do
  resources :favorites

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :buses, :only => []

  
  get "arrival/select"
  get "arrival/show"
  get "arrival/select_line"
  get "arrival/find_street"
  get "arrival/find_intersection"
  get "arrival/find_stop"
  
  root :to => 'arrival#select'
end

app/models/bus.rb
class Bus < ActiveRecord::Base
  has_many :favorites
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :bus

  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :account_type

  validates_uniqueness_of :email
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
	  data = access_token['extra']['user_hash']
	  if user = User.find_by_email(data["email"])
	    user
	  else # Create a user with a stub password. 
	    User.create(:email => data["email"], :password => Devise.friendly_token[0,20], :account_type => 'facebook') 
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # layout :detect_browser

  # private
  # MOBILE_BROWSERS = ["android", "ipod", "opera mini", "blackberry", "palm","hiptop","avantgo","plucker", "xiino","blazer","elaine", "windows ce; ppc;", "windows ce; smartphone;","windows ce; iemobile", "up.browser","up.link","mmp","symbian","smartphone", "midp","wap","vodafone","o2","pocket","kindle", "mobile","pda","psp","treo"]

  # def detect_browser
  #   agent = request.headers["HTTP_USER_AGENT"].downcase
  #   MOBILE_BROWSERS.each do |m|
  #     return "mobile_new" if agent.match(m)
  #   end
  #   return "layout_new"
  # end
end

app/controllers/arrival_controller.rb
class ArrivalController < ApplicationController
  def select
  	@buses = Bus.all
  	@line = session[:line_value]
  	@stop = session[:stop]
  end
  
  def select_line
    @buses = Bus.all  
  end

  def find_street
    agent = Mechanize.new
    agent.get("http://www.etr.gov.ar/getData.php?accion=getCalle&idLinea=#{params[:line]}")
    streets_json = agent.page.content

    @streets = ActiveSupport::JSON.decode(streets_json)
  end

  def find_intersection
    agent = Mechanize.new
    agent.get("http://www.etr.gov.ar/getData.php?accion=getInterseccion&idLinea=#{params[:line]}&idCalle=#{params[:street][:id]}")
    intersections_json = agent.page.content

    @intersections = ActiveSupport::JSON.decode(intersections_json)
    @street = params[:street][:id]
  end

  def find_stop
    agent = Mechanize.new
    agent.get("http://www.etr.gov.ar/getData.php?accion=getInfoParadas&idLinea=#{params[:line]}&idCalle=#{params[:street]}&idInt=#{params[:intersection][:id]}")
    session[:stop] = agent.page.links.first.text
    session[:line_value] = Bus.find_by_line_id(params[:line]).value
    redirect_to arrival_select_path
  end

  def show
    agent = Mechanize.new
    agent.post("http://www.etr.gov.ar/getSmsResponse.php", {"parada" => "#{params[:stop]}", "linea"=>"#{params[:line]}"})
    @llegada = agent.page.content
  end
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  # GET /buses
  # GET /buses.xml
  def index
    @buses = Bus.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @buses }
    end
  end

  # GET /buses/1
  # GET /buses/1.xml
  def show
    @bus = Bus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bus }
    end
  end

  # GET /buses/new
  # GET /buses/new.xml
  def new
    @bus = Bus.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bus }
    end
  end

  # GET /buses/1/edit
  def edit
    @bus = Bus.find(params[:id])
  end

  # POST /buses
  # POST /buses.xml
  def create
    @bus = Bus.new(params[:bus])

    respond_to do |format|
      if @bus.save
        format.html { redirect_to(buses_path, :notice => 'Bus was successfully created.') }
        format.xml  { render :xml => @bus, :status => :created, :location => @bus }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bus.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /buses/1
  # PUT /buses/1.xml
  def update
    @bus = Bus.find(params[:id])

    respond_to do |format|
      if @bus.update_attributes(params[:bus])
        format.html { redirect_to(@bus, :notice => 'Bus was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bus.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /buses/1
  # DELETE /buses/1.xml
  def destroy
    @bus = Bus.find(params[:id])
    @bus.destroy

    respond_to do |format|
      format.html { redirect_to(buses_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_filter :authenticate_user!
  # GET /favorites
  # GET /favorites.xml
  def index
    @favorites = current_user.favorites

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.xml
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/new
  # GET /favorites/new.xml
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  # POST /favorites.xml
  def create
    @favorite = Favorite.new(params[:favorite])
    @favorite.user = current_user
    
    respond_to do |format|
      if @favorite.save
        format.html { redirect_to(favorites_url, :notice => 'Favorite was successfully created.') }
        format.xml  { render :xml => @favorite, :status => :created, :location => @favorite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /favorites/1
  # PUT /favorites/1.xml
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to(favorites_url, :notice => 'Favorite was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.xml
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to(favorites_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def facebook_like
		content_tag :iframe, nil, :src => "http://www.facebook.com/plugins/like.php?href=#{CGI::escape(request.url)}&layout=standard&show_faces=false&width=320&action=like&font=arial&colorscheme=light&height=10", :scrolling => 'no', :frameborder => '0', :allowtransparency => true, :id => :facebook_like
	end

  def favorite_is_present
    Favorite.find_by_bus_id_and_user_id_and_stop(Bus.find_by_value(params[:line]),current_user,params[:stop])
  end
end

app/helpers/arrival_helper.rb
module ArrivalHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/arrival/find_intersection.html.erb
<div class="page-header">
<h1>No sé la parada <small>Buscar por intersección de calles.</small></h1>
</div>

<div class="row">
  <div class="span14">
		<% form_tag(arrival_find_stop_path, :method => 'get', :class=> "form-stacked") do %>
			<fieldset>
				<legend>Paso 3 de 3</legend>
				<div class="clearfix">
					<label for="intersection"> Intersección </label>
					<div class="input">
						<%= select("intersection", "id", @intersections.collect {|street| [street['desc'],street['id']]} ) %>
						<span class="help-block">Seleccioná la segunda calle de la intersección</span>
					</div>
				</div>
				<%= hidden_field_tag "line", params[:line] %>
				<%= hidden_field_tag "street", @street%>

				<div class="actions">
					<%= submit_tag "Buscar", :class => "btn primary" %>
				</div>
			</fieldset>
		<% end %>
	</div>
</div>

app/views/arrival/find_street.html.erb
<div class="page-header">
<h1>No sé la parada <small>Buscar por intersección de calles.</small></h1>
</div>

<div class="row">
  <div class="span14">
		<% form_tag(arrival_find_intersection_path, :method => 'get', :class=> "form-stacked") do %>
			<fieldset>
				<legend>Paso 2 de 3</legend>
				<div class="clearfix">
					<label for="street"> Calle </label>
						<div class ="input">
							<%= select("street", "id", @streets.collect {|street| [street['desc'],street['id']]}, {:class => 'medium'} ) %>
							<span class="help-block">Seleccioná la primera calle de la intersección.</span>
						</div>
					</div>				
				<%= hidden_field_tag "line", params[:line] %>
			</fieldset>

			<div class="actions">
				<%= submit_tag "Buscar", :class =>"btn primary" %>
			</div>
		<% end %>
	  </div>
</div>

app/views/arrival/select.html.erb
<div class="page-header">
<h1>Sé la parada <small>Seleccioná la línea y parada que ya conocés.</small></h1>
</div>

<div class="row">
  <div class="span14">
		<% form_tag(arrival_show_path, :method => 'get', :class=> "form-stacked") do %>
			<fieldset>
				<legend>Adelante.</legend>
				<div class="clearfix">
					<label for="line"> Línea </label>
					<div class ="input">
						<%= select_tag "line", options_from_collection_for_select(@buses, "value", "name", @line), :class => "medium" %> 
					</div>
				</div>

				<div class="clearfix">
					<label for="stop"> Parada </label>
					<div class="input">
						<%= text_field_tag "stop", @stop, :class => "medium" %>
					</div>
				</div>
				
				<div class="actions">
					<%= submit_tag "Consultar", :class =>"btn primary" %>
				</div>
			</fieldset>
		<% end %>
  </div>
</div>

app/views/arrival/select_line.html.erb
<div class="page-header">
<h1>No sé la parada <small>Buscar por intersección de calles.</small></h1>
</div>

<div class="row">
  <div class="span14">
		<% form_tag(arrival_find_street_path, :method => 'get', :class=> "form-stacked") do %>
			<fieldset>
				<legend>Paso 1 de 3</legend>
				<div class="clearfix">
					<label for="line"> Línea </label>
					<div class ="input">
						<%= select_tag "line", options_from_collection_for_select(@buses, "line_id", "name"), :class => "medium" %> 
						<span class="help-block">Seleccioná la línea cuya parada deseás conocer.</span>
					</div>
				</div>

				<div class="actions">
					<%= submit_tag "Buscar", :class =>"btn primary" %>
				</div>
			</fieldset>
		<% end %>
  </div>
</div>

app/views/arrival/show.html.erb
<div class="page-header">
<h1>Llegada.</small></h1>
</div>

<div class="row">
  <div class="span5">
  <p><%= @llegada %></p>
  </div>

  <div class="span4">
    <% if user_signed_in? %>
      <% unless favorite_is_present%>
      <%= link_to "Agregar a favoritos", Favorite.create!(:bus => Bus.find_by_value(params[:line]), :stop => params[:stop], :user => current_user) %><br>
      <% end %>
    <% end %>
    <%= link_to "Volver", :back %>
  </div>

</div>

app/views/buses/edit.html.erb
<h1>Editing bus</h1>

<%= render 'form' %>

<%= link_to 'Show', @bus %> |
<%= link_to 'Back', buses_path %>

app/views/buses/index.html.erb
<h1>Listing buses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Id line</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buses.each do |bus| %>
  <tr>
    <td><%= bus.name %></td>
    <td><%= bus.line_id %></td>
    <td><%= bus.value %></td>
    <td><%= link_to 'Show', bus %></td>
    <td><%= link_to 'Edit', edit_bus_path(bus) %></td>
    <td><%= link_to 'Destroy', bus, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bus', new_bus_path %>

app/views/buses/new.html.erb
<h1>New bus</h1>

<%= render 'form' %>

<%= link_to 'Back', buses_path %>

app/views/buses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bus.name %>
</p>

<p>
  <b>Id line:</b>
  <%= @bus.id_line %>
</p>

<p>
  <b>Value:</b>
  <%= @bus.value %>
</p>


<%= link_to 'Edit', edit_bus_path(@bus) %> |
<%= link_to 'Back', buses_path %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>¡Favorito agregado exitosamente!</p>

<%= link_to 'Volver', favorites_path %>

app/views/layouts/layout_new.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title>Cuándo Llegará</title>
    <meta name="description" content="Alternativa para visualizar la llegada de colectivos en la ciudad de Rosario">
    <meta name="author" content="Bruno Bonamin - bruno.bonamin@gmail.com">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag 'bootstrap' %>
    <style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }

      /* The white background content wrapper */
      .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }

      /* Styles you shouldn't keep as they are for displaying this base example only */
      .content .span10,
      .content .span4 {
        min-height: 500px;
      }
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 19px;
        border-left: 1px solid #eee;
      }

      .topbar .btn {
        border: 0;
      }

    </style>


  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes" />   
  <link rel="apple-touch-icon" href="/images/cllg.png">
  <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png">

  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>

  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6820257-6']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
  </head>

  <body>
  <div class="container">
    <script type="text/javascript">
      var admob_vars = {
       pubid: 'a14e57a870772ce', // publisher id
       bgcolor: 'FFFFFF', // background color (hex)
       text: '000000', // font-color (hex)
       test: true // test mode, set to false to receive live ads
      };
    </script>
    <script type="text/javascript" src="http://mmv.admob.com/static/iphone/iadmob.js"></script>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Cuándo Llegará</a>
          <ul class="nav">
            <!-- <li class="active"> -->
            <li>
              <% if user_signed_in? %>
                <%= link_to "Favoritos", favorites_path %></li>
                <li><%= link_to "Sé la parada", arrival_select_path %></li>
              <% else %>
                <%= link_to "Sé la parada", arrival_select_path %></li>
              <% end %>
            <li><%= link_to "No sé la parada", arrival_select_line_path %></li>
          </ul>
          <div class="pull-right" style="padding-top:10px">
            <% if user_signed_in? %>
              <li> <%= link_to current_user.email, edit_user_registration_path(current_user) %>. <%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Inicie sesión", new_user_session_path %> o <%= link_to "regístrese", new_user_registration_path %> para guardar favoritos.</li>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        <%= yield %>
        <div class="row">
          <div class="span2">
            <a href="http://twitter.com/share" class="twitter-share-button" data-text="Cuándo Llegará - Llegada de colectivos en #Rosario en un formato más adecuado. También para smartphones!" data-count="horizontal" data-via="bbonamin" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
          </div>
          <div class="span2">
            <iframe src="http://www.facebook.com/plugins/like.php?app_id=224649547582769&amp;href=http%3A%2F%2Fcuandollegara.com.ar%2F&amp;send=false&amp;layout=button_count&amp;width=320&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=verdana&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:320px; height:21px;" allowTransparency="true"></iframe>
          </div>
        </div>
      </div>

      <footer>
        <p> Una alternativa al <a href="http://www.etr.gov.ar/cuandollega.html" target="_blank">Cuándo Llega</a> de Rosario, Santa Fe.

          <p align="justify">
          <b>Cuándo Llegará</b> no tiene afiliación alguna con el <a href="http://www.etr.gov.ar">Ente de Transporte de Rosario</a>. </p>

          <p align="justify">
          Creado por <a href="http://bonamin.com.ar">Bruno Bonamin</a>, 2011 &copy; <br>
          Código fuente disponible en <a href="http://https://github.com/bbonamin/Cuandollegara">GitHub </a></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/mobile_new.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title>Cuándo Llegará</title>
    <meta name="description" content="Alternativa para visualizar la llegada de colectivos en la ciudad de Rosario">
    <meta name="author" content="Bruno Bonamin - bruno.bonamin@gmail.com">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag 'bootstrap' %>
    <style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 70px;
        padding-right:0px;
      }
      .container {
        width:90%;
        padding-left: 0;
        padding-right:0;
      }
      .span16 {
        width:100%;
      }
      .actions {
        padding: 1em -1em 1em 1em;
        width:90%;
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }

      /* The white background content wrapper */
      .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }

      /* Styles you shouldn't keep as they are for displaying this base example only */
      /*.content .span10,
      .content .span4 {
        min-height: 500px;
      }*/
      [class*="span"] {
        display: inline;
        float: left;
        margin-left: 2em;
      }
      form .input {
        margin-left: 1em;
      }
      .form-stacked {
        padding-left: 1em;
      }
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 5px;
        border-left: 1px solid #eee;
      }

      .topbar {
        /*display:none;*/
      }
      .topbar .btn {
        border: 0;
      }
      .span14 {
        width: 220px;
      }

      .span5 {
        width: 270px;
      }
      a {
        padding-left: 1.5em;
      }
    </style>


  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes" />   
  <link rel="apple-touch-icon" href="/images/cllg.png">
  <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>

  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6820257-6']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
  </head>

  <body>
  <div class="container">
    <script type="text/javascript">
      var admob_vars = {
       pubid: 'a14e57a870772ce', // publisher id
       bgcolor: 'FFFFFF', // background color (hex)
       text: '000000', // font-color (hex)
       test: false // test mode, set to false to receive live ads
      };
    </script>
    <script type="text/javascript" src="http://mmv.admob.com/static/iphone/iadmob.js"></script>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <ul class="nav">
            <li>
              <% if user_signed_in? %>
                <%= link_to "Favs", favorites_path %></li>
                <li><%= link_to "Parada", arrival_select_path %></li>
              <% else %>
                <%= link_to "Por parada", arrival_select_path %></li>
              <% end %>
            <li><%= link_to "Buscar", arrival_select_line_path %></li>
          </ul>
          <div class="pull-right" style="padding-top:0.7em">
              <% if user_signed_in? %>
                <%= link_to current_user.email, edit_user_registration_path(current_user) %>
              <% else %>
                <%=link_to "Identificarme", new_user_session_path %>
              <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        <%= yield %>
      <div class="row" style="margin-top:1.5em">
          <div class="span2">
            <a href="http://twitter.com/share" class="twitter-share-button" data-text="Cuándo Llegará - Llegada de colectivos en #Rosario en un formato más adecuado. También para smartphones!" data-count="horizontal" data-via="bbonamin" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
          </div>
          <div class="span2">
            <iframe src="http://www.facebook.com/plugins/like.php?app_id=224649547582769&amp;href=http%3A%2F%2Fcuandollegara.com.ar%2F&amp;send=false&amp;layout=button_count&amp;width=320&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=verdana&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:320px; height:21px;" allowTransparency="true"></iframe>
          </div>
        </div>
      </div>

      <footer>
        <p> Una alternativa al <a href="http://www.etr.gov.ar/cuandollega.html" target="_blank">Cuándo Llega</a> de Rosario, Santa Fe.

          <p align="justify">
          <b>Cuándo Llegará</b> no tiene afiliación alguna con el <a href="http://www.etr.gov.ar">Ente de Transporte de Rosario</a>. </p>

          <p align="justify">
          Creado por <a href="http://bonamin.com.ar">Bruno Bonamin</a>, 2011 &copy;</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>